# Generated by Django 5.2.4 on 2025-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(default='2025-01-01')),
                ('start_at', models.TimeField(default='08:00:00')),
                ('end_at', models.TimeField(default='08:00:00')),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(default='event_images/default_event_image.jpg', upload_to='event_images/')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
