# Generated by Django 5.2.4 on 2025-09-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEvent', '0002_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='booking',
            table=None,
        ),
    ]
