# Generated by Django 5.2.4 on 2025-09-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvent', '0006_category_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Art', 'Art'), ('Sports', 'Sports'), ('Workshops', 'Workshops'), ('Food', 'Food'), ('Family', 'Family')], default='Music', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
