# Generated by Django 5.2.4 on 2025-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEvent', '0008_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
