# Generated by Django 5.2.4 on 2025-08-11 18:44

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appUser.user',),
            managers=[
                ('attendee', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
