# Generated by Django 5.2.4 on 2025-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('ATTENDEE', 'Attendee')], default='ADMIN', max_length=50),
        ),
    ]
