# Generated by Django 5.2.4 on 2025-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic_default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
