# Generated by Django 5.2.4 on 2026-06-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'Attendee', 'verbose_name_plural': 'Attendees'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('ATTENDEE', 'Attendee')], default='ATTENDEE', max_length=50),
        ),
    ]
